name: Build CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: -f "C:\Users\balle\OneDrive\Desktop\commons-email-1.3.2-src\pom.xml" mvn clean test
